### ISSUE TITLE
Issue with Yeti Sharing Declaration

### ISSUE THREAD

**Issue by matthieu-farcot** [BII-Lab/Macaque_Project#15]
Hi

2 issues with Yeti sharing declaration (https://github.com/BII-Lab/Yeti-Project/blob/master/doc/DataSharingDeclaration.md)
- Yeti Data is only mentioned in intro (definition section). All of document refers to "data" or "Data". Should "data" or "Data" == "Yeti Data", this should be clarified.
- Section 5 (Participant Use of Data) is clearly in contradiction with the goal of the project. Since by default all Data is confidential (unless exceptions listed in sub-section 2.ii apply or non-confidential declaration is done as requested in sub section 2.iii), as stated in said section 5, why contribute pcap files? The goal of this project is to share and do research. 

We would like those two points to be clarified (and the draft mention to be removed).

Dr Matthieu Farcot
Legal Advisor
CIRCL - Computer Incident Response Center Luxembourg
c/o smile - "security made in Letzebuerg" GIE
41, av. de la gare Luxembourg L-1611 - (352) 247 88444
info@circl.lu - www.circl.lu

**Comment by shane-kerr** [comment]
Dr. Matthieu Farcot,

Thanks for taking the time to look at this - your feedback is much appreciated!

I've updated the statement based on your recommendations. These are documented in the pull request #18, which hopefully answers your concerns.
